# Renal tubular acidosis

Free [H^+^] is nM, but we need to excrete mmoles (1 mmol / kg on Western diet), therefore must be buffered by NH~4~, PO~4~...

### Classification of RTA  

+  type II (pRTA) *impaired reabsorption of HCO3*  


+  type I (dRTA) *inability to secrete acid* 
    +  *complete dRTA systemic acidosis (impaired ammoniagenesis)* 
    +  *partial dRTA no acidosis (preserved ammoniagenesis)*  

    
+  type IV *impaired ammoniagenesis (due to hyperK); deficient aldosterone or CD abnormality*  


+  type III (mixed) *CA inhibition*  


+  RTA in CKD *HCMA when GFR \< 30; WGMA when GFR \< 15*  

### Associations

- dRTA CaP stones (alkaline urine, hypocitraturia)  
- nephrocalcinosis (in inherited but NOT acquired forms)  
- osteoporosis  

### Investigation of suspected RTA

+  UAG & FENaHCO~3~  
+  urine pH (never \< 5.5 in dRTA)  
+  in suspected pRTA 
    +  *tubular reabsorption of phosphate (TRP = 100 - FEPO~4~) \< 85 %* 
    +  *glycosuria, aminoaciduria, LMW proteinuria*  
+  in suspected dRTA 
    +  *furosemide-fludrocortisone (FF) test (failure to achieve pH \< 5.3 , 3 -- 4 hrs after 40 -- 80 mg / 1 mg)* 
    +  *UCa \> 4 mg / kg / day (or spot UCa/Cr \> 0.2) in type I RTA* 
    +  *USS / KUB (medullary nephrocalcinosis in type I RTA)* 
    +  *urinary citrate (low in type I RTA; high in type II / IV RTA)*  
+  kidney biopsy (to detect subclinical TIN)  
    
To meausure urine pH must use a well-calibrated pH meter - and either analyse immediately (literally straight away) or collect under mineral oil and can then test at leisure.  (So if pH meter being housed in the lab then must collect under mineral oil.)  Otherwise CO2 will diffuse in, be converted to bicarbonate and raise the pH (i.e. risk of false-positive F&F test leading to erroneous dRTA diagnosis).  

Test urinary RBP (retinol binding protein) as the most sensitive marker of proximal renal tubular dysfunction - good in sarcoid, Sjogren's etc.  Good for diagnosis and for tracking disease activity.  


### Causes

<!-- +  pRTA (isolated)  -->
<!--     +  inherited  -->
<!--     +  acquired *topiramate*   -->


<!-- +  pRTA (with Fanconi)  -->
<!--     +  inherited *NBCe1A (AR with ocular abnormalities)*  -->
<!--     +  metabolic *Wilson's, cystinosis, fructose intolerance, Dent's, mitochondrial cytopathies*  -->
<!--     +  dysproteinaemia *myeloma, LCDD, LCFS is κ in 96 %, amyloid*  -->
<!--     +  tubulointerstitial *interstitial nephritis (inc. Sjogren's), allograft rejection*  -->
<!--     +  drugs *(Abx / cART)* *tenofovir, lamivudine, aminoglycosides, outdated tetracyclines*  -->
<!--     +  drugs *(other) cisplatin, valproate, lenalinomide*  -->
<!--     +  toxins *Pb, Hg, Cd, aristolochic acid*   -->


<!-- +  dRTA  -->
<!--     +  inherited *AEI (AR), H-ATPase B1 (AR with SNHL), H-ATPase A4 (AR)*  -->
<!--     +  tubulointerstitial *chronic pyelonephritis, chronic TIN, obstructive uropathy, sickle cell, rejection*  -->
<!--     +  autoimmune *hypergammaglobulinaemia, SLE, Sjogren's, chronic active hepatitis, PBC*  -->
<!--     +  drugs *Li^+^, amphoterecin, toluene*  -->
<!--     +  nephrocalcinosis *hyperPTH, idiopathic hypercalciuria, MSK*   -->


<!-- +  type IV  -->
<!--     +  low renin *DM, NSAIDs, CNIs, β--*  -->
<!--     +  high renin *Addisons, CAH, ACEi, ARB, heparin, ketoconazole*  -->
<!--     +  abnormal CD *TIN, spiro, amiloride, trimethoprim*   -->


<!-- +  type III  -->
<!--     +  inherited *CAII (AR with osteopetrosis / cerebral calcification)*  -->
<!--     +  acquired *topiramate (CA inhibition)*   -->

```{r, echo=FALSE, message=FALSE, warning=FALSE}
source('~/OneDrive - University of Edinburgh/R files/R Scripts/Markdown_tables.R')
# df_table <- read.csv("tables/RTA_expanded.csv", header = FALSE)
df_table <- read.csv("tables/RTA_expanded.csv", header = FALSE)

df_table %>% table_3cols(caps = T)

```

Sjogrens classically causes a dRTA (but can also cause pRTA if interstitial nephritis).  Autoimmune dRTA is Sjogrens in 80 - 90%.  Subclinical tubular involvment in 30% Sjorens.  Often associated with hypocitruria and low-grade features of Fanconi syndrome.  Treat CIN with MMF or pred / RTX.  Treat dRTA with K citrate.  Autoantibodies to H+-ATPase or bicarb exchanger.  


Mitochondrial cytopathy: raised CK, abnormal number of microchondria (EM).

<!-- ### Treatment -->

<!-- +  K citrate  -->
<!-- +  +/- NaHCO~3~  -->

#### Fanconi syndrome

In adults, usually acquired:

- tenfovir and other drugs  
- heavy metals  
- LCCD  
- post-Tx  


Check for:

- LMWH proteinuria (e.g. retinol binding protein; high uPCR with a negative dip)  
- uricosuria  
- phosphaturia  
- renal glycosuria  

LMW proteinuria is the most sensitive test (because megalin is the most energy-sensitive process and therefore most vulnerable to becoming disrupted).  Glycosuria appears last (least energy-sensitive process).    
