# Polyuria

Usually defined as a urine volume \> 3.0 L per day (or 40 ml/kg body weight per day or 2 ml/hr).  

<br>
<br>

## Causes

[Differential diagnosis](https://pubmed.ncbi.nlm.nih.gov/26687922/) of a polyuria-polydipsia syndrome:  

1)  water diuresis (high C~H2O~): **U~Osm~ \< 100**

    + primary polydipsia 
    + iatrogenic water overload (IV 5%G) 
    + AVP-D (central \*\*\* or gestational DI - may be complete or partial)  
    + AVP-R (nephrogenic DI - may be complete or partial)  

<br>

2)  solute diuresis (high C~Osm~): **U~Osm~ \> 300**

    + electrolytes: pure NaCl (IV NaCl, dietary NaCl, salt-wasting nephropathy)  
    + electrolytes: HCO3 (vomiting...)  
    + electrolytes: ketones (DKA...)  
    + non-electrolytes: urea (high-protein nutritional supplements, post-rhabdomyolysis, massive haematoma)  
    + non-electrolytes: glucose  
    + mixed urea and NaCl: post-obstructive uropathy, resolving ATI  

<br>

3)  mixed: **U~Osm~ 100 -- 300**

    + partial DI (central) 
    + partial DI (nephrogenic) 
    + CKD 
    + tubular injury, diuretics, ATN recovery 

<br>
<br>

Water diuresis may be appropriate (polydipsia, IV dextrose) or inappropriate (DI). Similarly, solute diuresis may be appropriate (IV NaCl, post-obstructive) or inappropriate (hyperglycaemia, high-protein feed, salt-wasting nephropathy).  

<br>

During prolong diuresis from any initiating cause, washout of the medullary concentration gradient can lead to a temporary inability to concentrate the urine (i.e. an acquired NDI).  Thus, the initial UOsm will tend towards isothenuria.  Therefore even with heavy [solute diuresis](https://pubmed.ncbi.nlm.nih.gov/9125003/), UOsm ranges 300 -- 500 mOsm.  

<br>

\*\*\* *Arginine-vasopressin is synthesised in the magnocellular neurones in the supraoptic & paraventricular nuclei of the hypothalamus and stored and released from the posterior pituitary. Cranial DI is caused by damage to supraoptic / paraventricular nuclei in hypothalamus (NOT merely compression of pituitary).*  

<br>

## Investigation of polyuria

See [Bhasin & Velez, 2016](https://pubmed.ncbi.nlm.nih.gov/26687922/) & [Oster et al., 1997](https://pubmed.ncbi.nlm.nih.gov/9125003/).  

First exclude common causes (EtOH, DM, Ca2+, K+, CKD, drugs...)

Then measure UOsm (see above):

+  if water diuresis: classically water deprivation test but now better copeptin testing (see below)  

+  if solute diuresis: 24 hr urine collection:
    - *urine Osm, Cr, Na, K, Cl, urea, glucose*  
    - *...and also pH, specific gravity*
    - *calculate daily osmole excretion (see below)*    

+  if mixed: both

<br>


```{block2, type='eqnpanel'}
\begin{equation}
  \text{daily total solute excretion, } U_{TS} =U_{Osm} \times V
  (\#eq:excretion-totalsolute)
\end{equation}

\begin{equation}
  \text{daily electrolyte solute excretion, } U_{E} =2\times (U_{Na} + U_{K}) \times V
  (\#eq:excretion-electrolyte)
\end{equation}

\begin{equation}
  \text{daily non-electrolyte solute excretion, } U_{NE} = U_{TS} - U_{E}
  (\#eq:excretion-nonelectrolyte)
\end{equation}

```

Use Cr excretion to assess completeness of 24 hr collection.  [Expect](https://pubmed.ncbi.nlm.nih.gov/25858764/) 150 +/- 40 micromol/kg in women or 190 +/- 40 micromol/kg in men.  

Usual daily osmolar exretion is 10 mOsm/kg on a standard Western diet:   
 - when [this exceeds 900 mOsm](https://pubmed.ncbi.nlm.nih.gov/26687922/), urine volumes are appreciably larger  
 - when [this exceeds 1200 - 1400 mOsm](https://pubmed.ncbi.nlm.nih.gov/9125003/), there is a *bona fide* solute diuresis  

<br>

Then assess electrolyte vs. non-electrolyte solute excretion:  

- if electrolyte solute excretion, U<sub>E</sub> \> 600 mOsm = electrolyte solute diuresis    
- if non-electrolyte solute excretion, U<sub>NE</sub> \> 600 mOsm = non-electrolyte solute diuresis    

<br>

In electrolyte solute diuresis, look at urine pH and uAG to determine main anion.  If very +ve uAG and alkaline urine (pH > 7.4) then likely to be bicarbonate.  If very +ve uAG and non-alkaline urine (pH < 7.4) then may be ketones or anionic medications.  If very -ve uAG then may be ammonium chloride.  If within 50 - 70 mM of zero, then likely to be NaCl diuresis.  

<br>

Non-electrolyte may be gluose, urea (expect > 250 mM urine urea) or mannitol.  70 g protein is be metabolised into 400 mmol urea.  

<br>
<br>

## Uses for copeptin testing  

### Assay details

Co-peptin is highly stable ex-vivo: can store samples at room temperature for 7 days prior to analysis.  Normal healthy values under basal conditions = 1 - 14 pM (median 4 pM).  

<br>
<br>

### Polyuria-polydipsia (hypotonic polyuria)  

Role of copeptin testing most clearly established.  

See [review](https://pubmed.ncbi.nlm.nih.gov/26794439/) as well as [original description](https://pubmed.ncbi.nlm.nih.gov/25768671/) of this approach and [validation in NEJM](https://pubmed.ncbi.nlm.nih.gov/30067922/) of the saline-stimulated copeptin test.  

First use a random copeptin (obtained without prior water deprivation) to differentiate AVP-R (NDI = high copeptin) from either AVP-D (CDI) or primary polydipsia (= low copeptin).  Using a cut-off of 21.4 pM, can differentiate AVP-R from alternative causes with 100% sensitivity and specificity.  

Therefore:    

- random copeptin (without water deprivation) high (\> 21.4 pM) = AVP-R (NDI)  
- random copeptin (without water deprivation) low (\< 21.4 pM) = partial AVP-D (CDI) or primary polydipsia - proceed to stimulated copeptin test below  
- random copeptin (without water deprivation) very low (\< 2.6 pM) = complete AVP-D - no need for simulated copeptin test  

<br>

To differentiate AVP-D from primary polydipsia, use [saline-stimulated copeptin test]:  

- infuse 3% NaCl over 3 hrs then measure co-peptin once PNa \> 150 mM  
- low co-peptin (\< 4.9 pM) = ADP-D (CDI) 
- high co-peptin (\> 4.9 pM) = primary polydipsia  
- less cumbersome alternative to standard water-deprivation test (17 hrs)...  
- ...and also more accurate (AUC 0.97!)  

<br>
<br>

### Hypernatraemia

Evolving [role](https://pubmed.ncbi.nlm.nih.gov/35137148/) in identifying AVP-D (CDI) and need for ddAVP treatment.  Main evidence from [Co-MED observational study](https://pubmed.ncbi.nlm.nih.gov/29422070/) of patients presenting to A&E with severe hypoNa (Na > 155 mM).  

Low copeptin (\< 4.4 pM) = AVP-D (CDI).  

Copeptin levels tend to be very high in other causes of hyperNa (i.e. dehydration, salt overload, AVP-R): median c. 50 pM.  

Urea levels also correlated pretty well with diagnosis (\< 5 mM = AVP-D with 98% specificity and 100% sensitivity).  Median c. 18 mM in other causes of hyperNa.  

Urine osmolality c. 300 mOsm in AVP-D and AVP-R c.f. 500 mOsm in dehydration or salt overload.  

If there is an associated polyuria-polydipsia syndrome then can evaluate as above.  

NB - think my current slides on this may be incorrect! - need to amend and also hyperNa section of nephromaths.  

<br>
<br>

### Hyponatraemia

No major role for copeptin testing.  Because (Hoorne) we have the perfect biomarker of AVP action: UOsm and because copeptin levels are [elevated in most cases](https://pubmed.ncbi.nlm.nih.gov/36974717/) of hypoNa, including SAID, hypo- and hypervolaemia.  Possibly [a role](https://pubmed.ncbi.nlm.nih.gov/36974717/) in identifying the very rare cases of nephrogenic SAID, prior to genetic testing.  
