# Magnesium

## Mg homeostasis 

99 % of total body Mg is held in bone and intracellular stores.  Intake is around 10 mmoles per day; 50% excretion in the urine and 50% in stool.  

Intestinal absorption is through paracellular and active transcellular (TRPM6, TRPM7) pathways.  

[Renal tubular reabsorption](https://www.kidneyfish.net/post/ppis-and-magnesium/) is through paracellular (claudin-dependent) pathways in the TALH (70%) and transcellular (EGF / TRPM6-dependent) transport in the DCT (10%).  


## Hypomagnesaemia  

### Consequences  

- ECG changes (mimics hyperK and then torsades)  
- hypocalcaemia (combination of impaired PTH secretion and peripheral PTH resistance)  
- [hypokalaemia](https://www.kidneyfish.net/post/magnesium-and-potassium/)


### Differential diagnosis of hypomagesaemia

<!-- +  with hyperK  -->
<!--     +  *CNIs*  -->
<!--     +  *K-sparing diuretics*  -->
<!--     +  *poorly-controlled DM*   -->
<!-- +  with hypoK  -->
<!--     +  *PPIs*  -->
<!--     +  *diuretics (loop / thiazides)*  -->
<!--     +  *Bartter / Gitelman*  -->
<!--     +  *Conn*  -->
<!--     +  *amphotericin*   -->
<!-- +  with hypoCa  -->
<!--     +  *PPIs*  -->
<!--     +  *post-parathyroidectomy*  -->
<!--     +  *TRPM6 / claudin 16 mutations*   -->
<!-- +  isolated (rare)  -->
<!--     +  *EGF / NaKATPase-γ mutations*  -->
    
```{r, echo=FALSE, message=FALSE, warning=FALSE}
source('~/OneDrive - University of Edinburgh/R files/R Scripts/Markdown_tables.R')
df_table <- read.csv("tables/hypoMg.csv", header = FALSE)

df_table %>% table_2cols()

```
    
### Notes on specific causes

**PPIs**

Incidence of hypoMg with [PPIs](https://www.kidneyfish.net/post/ppis-and-magnesium/) \~ 1% after 3 months.  Mg wasting is through extra-renal pathways.  PPIs cause hypoNa, hypoK, hypoMg, hypoPO4.  

<br>

**Inherited tubulopathies**

- antenatal Bartter  
- familial hypoMg with hypercalicuria and nephrocalcinosis (claudins 16 or 19 AR)  
- hypoMg with secondary hypocalcaemia (TRPM6 variants AR = mixed intestinal and renal defects = profound hypoMg)  
- ADTKD-HNF1b (GU tract malformation with MODY5 diabetes)  
- Gitelman  
- EAST  
  
## Investigations

First, distinguish between GI and renal losses with urinary [Mg].  In the context of hypomagnesaemia:  UMgV > 1 mmol per day or FE~Mg~ \> 2 -- 3 % = renal loss.    

Next, if renal losses, measure UCaV.  If also high then likely TALH lesion; if isolated Mg-wasting then likely DCT lesion.  

<br>

```{block2, type='eqnpanel'}
\begin{equation}
  \text{fractional excretion, }FE_{Mg} = \frac{U_{Mg}}{P_{Mg} \times 0.7} \times \frac{P_{Creat}}{U_{Creat}}
  (\#eq:FEMg)
\end{equation}
    
```

When calculating FE~Mg~, divide the result by 0.7.  This is because P~Mg~ is multiplied by 0.7 to account for protein binding; only 70% of circulating Mg is free and therefore able to be filtered; 30% is albumin-bound [@agus1999].  



