# Renal tubular acidosis

## Classification of RTA  

+  **type II (pRTA)** = impaired reabsorption of HCO~3~  

+  **type I (dRTA)** = inability to secrete H^+^: 
    +  complete = systemic acidosis  
    +  incomplete = no systemic acidosis  

+  **type IV** = hypoaldosteronism (+/- impaired ammoniagenesis from hyperK)

+  **type III (mixed)** =  CA inhibition  

+  **RTA in CKD**: 
    + HCMA when GFR \< 30 
    + WGMA when GFR \< 15  

<br>
<br>


### Associations

- dRTA CaP stones (alkaline urine, hypocitraturia, hypercalciuria)    
- nephrocalcinosis (in inherited forms particularly)    
- osteoporosis  

<br>
<br>

### Investigation of suspected RTA

+ see [investigation of HCMA](#IxHCMA)
+  UAG & FENaHCO~3~  
+  urine pH (never \< 5.5 in dRTA)  

+  in suspected pRTA 
    +  *tubular reabsorption of phosphate (TRP = 100 - FEPO~4~) \< 85 %* 
    +  *glycosuria, aminoaciduria, LMW proteinuria*  
    
+  in suspected dRTA 
    +  *furosemide-fludrocortisone (FF) test (failure to achieve pH \< 5.3 , 3 -- 4 hrs after 40 -- 80 mg / 1 mg)* 
    +  *UCa \> 4 mg / kg / day (or spot UCa/Cr \> 0.2) in type I RTA* 
    +  *USS / KUB (medullary nephrocalcinosis in type I RTA)* 
    +  *urinary citrate (low in type I RTA; high in type II / IV RTA)*  
    
+  kidney biopsy (to detect subclinical TIN)  
    
<br>

Test urinary RBP (retinol binding protein) as the most sensitive marker of proximal renal tubular dysfunction - good in sarcoid, Sjogren's etc.  Good for diagnosis and for tracking disease activity.  

<br>

USS more sensitive than CT for nephrocalcinosis in the context of hypoparathyroidism, but CT more specific (Boyce JCEM 2013).  Plain films very insensitive.  Therefore prefer USS for screening (but consider CT for verification).  



### Causes

<!-- +  pRTA (isolated)  -->
<!--     +  inherited  -->
<!--     +  acquired *topiramate*   -->


<!-- +  pRTA (with Fanconi)  -->
<!--     +  inherited *NBCe1A (AR with ocular abnormalities)*  -->
<!--     +  metabolic *Wilson's, cystinosis, fructose intolerance, Dent's, mitochondrial cytopathies*  -->
<!--     +  dysproteinaemia *myeloma, LCDD, LCFS is κ in 96 %, amyloid*  -->
<!--     +  tubulointerstitial *interstitial nephritis (inc. Sjogren's), allograft rejection*  -->
<!--     +  drugs *(Abx / cART)* *tenofovir, lamivudine, aminoglycosides, outdated tetracyclines*  -->
<!--     +  drugs *(other) cisplatin, valproate, lenalinomide*  -->
<!--     +  toxins *Pb, Hg, Cd, aristolochic acid*   -->


<!-- +  dRTA  -->
<!--     +  inherited *AEI (AR), H-ATPase B1 (AR with SNHL), H-ATPase A4 (AR)*  -->
<!--     +  tubulointerstitial *chronic pyelonephritis, chronic TIN, obstructive uropathy, sickle cell, rejection*  -->
<!--     +  autoimmune *hypergammaglobulinaemia, SLE, Sjogren's, chronic active hepatitis, PBC*  -->
<!--     +  drugs *Li^+^, amphoterecin, toluene*  -->
<!--     +  nephrocalcinosis *hyperPTH, idiopathic hypercalciuria, MSK*   -->


<!-- +  type IV  -->
<!--     +  low renin *DM, NSAIDs, CNIs, β--*  -->
<!--     +  high renin *Addisons, CAH, ACEi, ARB, heparin, ketoconazole*  -->
<!--     +  abnormal CD *TIN, spiro, amiloride, trimethoprim*   -->


<!-- +  type III  -->
<!--     +  inherited *CAII (AR with osteopetrosis / cerebral calcification)*  -->
<!--     +  acquired *topiramate (CA inhibition)*   -->

```{r, echo=FALSE, message=FALSE, warning=FALSE}
source('~/OneDrive - University of Edinburgh/R files/R Scripts/Markdown_tables.R')
# df_table <- read.csv("tables/RTA_expanded.csv", header = FALSE)
df_table <- read.csv("tables/RTA_expanded.csv", header = FALSE)

df_table %>% table_3cols(caps = T)

```

<br>

Sjogrens classically causes a dRTA (but can also cause pRTA if interstitial nephritis).  Autoimmune dRTA is Sjogrens in 80 - 90%.  Subclinical tubular involvment in 30% Sjorens.  Often associated with hypocitruria and low-grade features of Fanconi syndrome.  Treat CIN with MMF or pred / RTX.  Treat dRTA with K citrate.  Autoantibodies to H+-ATPase or bicarb exchanger.  

<br>

Mitochondrial cytopathy: raised CK, abnormal number of microchondria (EM).

<!-- ### Treatment -->

<!-- +  K citrate  -->
<!-- +  +/- NaHCO~3~  -->

## Fanconi syndrome

In adults, usually acquired:

- tenfovir and other drugs  
- heavy metals  
- LCCD  
- post-Tx  


Check for:

- LMWH proteinuria (e.g. retinol binding protein; high uPCR with a negative dip)  
- uricosuria  
- phosphaturia  
- renal glycosuria  

LMW proteinuria is the most sensitive test (because megalin is the most energy-sensitive process and therefore most vulnerable to becoming disrupted).  Glycosuria appears last (least energy-sensitive process).    

<!-- <br> -->
<!-- <br> -->

<!-- ## Management -->

<!-- **Alkali supplements** for RTA (see [ESPN clinical practice points, NDT 2021](https://doi: 10.1093/ndt/gfab171)):   -->

<!-- - citrate unpalatable; longer half-life (as requires hepatic metabolism), more concentrated (2 - 3 mmmol/ml)   -->
<!-- - HCO3 associated with belching; less concentrated (1 mmol/ml)   -->
<!-- - microgranular formulation of K citrate and KHCO3 since 2017   -->
<!-- - usually 2 - 3 mmol/kg/day in adults (target HCO3, Cl, K and UCa); start at 60 mmol/day   -->
<!-- - may need additional KCl   -->
<!-- - avoid thaizides (will aggravate hypoK)   -->
<!-- - should have surveillance USS   -->

<!-- <br> -->

<!-- Uptodate:   -->

<!-- - see table 1 for options of alkali therapy   -->
<!-- - dRTA = start 80 - 120 mmol citrate (or HCO3) per day; usual maintenance 30 - 50 (or 1 - 2 mmol/kg/day)   -->
<!-- - pRTA needs much higher doses because therapeutic HCO3 load will exceed Tm and cause a bicarbonate diureis - therefore need 10 -- 15 mmmol/kg/day - may aggravate hypoK - so may need liquid sodium citrate as most concentrated   -->
<!-- - may need thiazides (to limit HCO3 wasting) / amiloride (to limit hypoK) in pRTA   -->
