# Appendix 2 - corollaries of urine osmolality equation {#app2}

In the [section on urine osmolality](#UOsm), we considered equation \@ref(eq:UOsm2): the relationship between osmolar load, urine volume and urine osmolality.  

This equation is reproduced here:  

```{block2, type='eqnpanel'}
\begin{equation}
  \text{urine volume, } V = \frac{OL}{U_{Osm}}
\end{equation}
      
```

We stated that this simple relationship can be used to explore a number of phenomena, such as:  

+ explaining why drinking seawater causes dehydration  
+ explaining why giving 0.9% NaCl can exacerbate hyponatraemia in some circumstances  
+ calculating the water intake that would cause hyponatraemia  
+ explaining why poor diet (low dietary solute intake) can cause hyponatraemia    

In this appendix, we consider these scenarios in more detail.  


## Why drinking seawater causes dehydration
The osmolality of seawater is ~1000 mOsm/kg.  Imagine 1L of seawater is ingested by somebody whose kidneys are only able to concentrate urine to a maximum of 900 mOsm/kg.  The osmolar load (1000 mOsm) must then be excreted in a minimum of 1.11L of urine (=1000/900), leading to a net loss of 0.11L of free water from the body.

## Why giving 0.9% NaCl can exacerbate hyponatraemia in some circumstances
Hyponatraemia may occur in the context of unregualted ADH release. In this context, urine osmolality is fixed so as to generate a concentrated urine. Suppose hyponatraemia develops in a person in whom ADH activation sets U~Osm~ at 600 mOsm/kg. If we were to administer 1L of intravenous 0.9% NaCl (=150 mM),  this would deliver an osmolar load of 300 mOsm. This load would be excreted in 0.5L of urine, leaving 0.5L of free water in the body to exacerbate the hyponatraemia. For this reason, hypertonic saline may be required in the treatment of severe or symptomatic hyponatraemia. 

## Calculating the water intake required to cause hyponatraemia
Hyponatraemia is a problem of excess body water.  In normal circumstances (with completely normal renal function and an intact ADH axis), the kidney is able to respond to water challange by producing a dilute urine.  The minimum possible urine osmolality will be ~50 mOsm/kg.  A typical daily osmolar load is around 10 mOsm per kg body weight (for somebody taking a Western diet); therefore ~700 mOsm in a 70 kg person. 

```{block2, type='eqnpanel'}
\begin{equation}
  \text{daily osmole excretion } = 10 \text{mOsm per kg body weight}
  (\#eq:dailyOL)
\end{equation}
```

This load can be accompanied by a free water intake of anything up to 14L per day (700/50), and that water can still be excreted in a urine that might be as dilute as 50 mOsm/kg. However, any water intake exceeding this threshold cannot be excreted and would be retained as free water, resulting in hyponatraemia.   
<br>

Therefore it should be apparent that in normal circumstances, the volume of water required to generated hyponatraemia through polydipsia is remarkably high (~14L per day).  However, in many patients who are unwell and may have low dietary solute intake and / or some limit to renal water excretion (e.g. mild CKD) then drinking a relatively low volume of water might result in hyponatraemia.  If daily solute intake = 350 mOsm and U~Osm~ cannot be lowered beyond 100 mOsm/kg then water intake in excess of 3.5L per day (350/100) would cause hyponatraemia.

## Why poor diet (low dietary solute intake) can cause hyponatraemia  
When dietary solute intake is low, the volume of urine used to excrete that osmolar load will also be low (for any given U~Osm~). This may limit water excretion, resulting in hyponatraemia.   

<br>

A diet that is relatively rich in carbohydrate will be low in solutes: carbohydrate is metabolised to CO~2~ and H~2~O, whereas protein is metabolised to urea [@thaler1998; @zotero-6730].  Thus hyponatraemia arising from this mechanism is commonly encountered in beer potomania and in patients on a "tea and toast diet".  
